"""Operation-specific and model-specific explanations for the public reference.

Keep this registry explicit. Shared enum/property names are not enough to infer
the behavior of an individual contract. Unreviewed entries stay visibly marked.
"""

OPERATIONS = {
    ("get", "/api/v1/driver/billing"): "Read the driver's billing mode, payment choices, billing history and store reconciliation facts. Use membership/store-status for the unified entitlement decision.",
    ("put", "/api/v1/driver/billing/mode"): "Change the driver's requested billing mode against the current revision; this does not by itself purchase or activate a plan.",
    ("get", "/api/v1/driver/membership"): "Read the driver's current membership, usage period, pending plan change and renewal preference.",
    ("get", "/api/v1/membership/plans"): "List driver membership catalog plans, term prices and benefit limits for the resolved country context.",
    ("put", "/api/v1/driver/membership/auto-renew"): "Change the server-managed membership renewal preference. Native-store subscription management remains a separate provider workflow.",
    ("post", "/api/v1/driver/membership/checkout"): "Create a membership checkout for a plan, term and supported provider; a checkout response is not proof of entitlement.",
    ("post", "/api/v1/driver/membership/pending-change/cancel"): "Cancel the identified pending membership change using the original membership revision; retain the currently effective entitlement facts.",
    ("get", "/api/v1/rider/membership"): "Read the rider's membership state and benefits in the current account context.",
    ("get", "/api/v1/rider/membership/plans"): "List membership plans for the rider audience; driver and rental plans are separate catalogs.",
    ("get", "/api/v1/rental-partner/membership/plans"): "List membership plans for rental partners; organization access and purchase readiness are checked separately.",
    ("get", "/api/v1/store-billing/operations/{operationId}"): "Read the caller's prepared store purchase operation and recovery state without starting another native purchase.",
    ("get", "/api/v1/auth/sessions"): "List the authenticated account's sessions so the owner can inspect and revoke eligible sessions.",
    ("delete", "/api/v1/auth/sessions/{id}"): "Revoke the selected session belonging to the authenticated account; possession of another session's ID does not grant authority.",
    ("get", "/api/v1/auth/passkeys"): "List the current account's registered passkey metadata; private authenticator key material is not returned.",
    ("post", "/api/v1/auth/passkeys/register/begin"): "Begin passkey registration and obtain the server challenge/options for the platform authenticator.",
    ("post", "/api/v1/auth/passkeys/register/complete"): "Verify the authenticator's response to the registration challenge and bind the accepted passkey to this account.",
    ("delete", "/api/v1/auth/passkeys/{id}"): "Remove the selected account-owned passkey through the protected security workflow.",
    ("post", "/api/v1/auth/social-link-intents/review"): "Read the protected pending social-link decision using its ceremony evidence; matching email addresses alone do not authorize linking.",
    ("post", "/api/v1/auth/social-link-intents/confirm"): "Complete an explicitly authorized pending social-account link after the required account proof.",
    ("post", "/api/v1/auth/social-link-intents/cancel"): "Cancel the pending social-link ceremony without creating the account connection.",
    ("get", "/api/v1/auth/social-connections"): "List the external sign-in connections attached to the authenticated account.",
    ("post", "/api/v1/auth/social-connections"): "Request an additional social sign-in connection using provider proof and the protected account-linking rules.",
    ("delete", "/api/v1/auth/social-connections/{id}"): "Disconnect an eligible external sign-in connection owned by the current account.",
    ("post", "/api/v1/auth/change-password"): "Change an existing password through authenticated identity validation; this is distinct from forgotten-password recovery.",
    ("post", "/api/v1/auth/set-password"): "Establish a password through the authenticated identity workflow where the account is eligible to do so.",
    ("get", "/api/v1/account/contact-details"): "Read the account's contact details and verification information before requesting a protected contact change.",
    ("put", "/api/v1/account/contact-details"): "Request an account contact-details update subject to identity conflicts and the applicable contact-proof requirements.",
    ("get", "/api/v1/account/setup-progress"): "Read persisted account setup progress so onboarding can resume after a restart.",
    ("get", "/api/v1/account/activity"): "Read the current account's activity information within the authorized account scope.",
    ("post", "/api/v1/account/activity/settings"): "Save account activity settings after server validation; a failed request must not be displayed as saved.",
    ("get", "/api/v1/account/security-events"): "Read the current account's security-event history for account-security review.",
    ("get", "/api/v1/account/security-preferences"): "Read account security-notification preferences, separate from device-local app-lock settings.",
    ("put", "/api/v1/account/security-preferences/login-email-alerts"): "Update the account's login email-alert preference through the authorized settings workflow.",
    ("get", "/api/v1/account/identity-verification/operations/outcome"): "Reconcile the original identity-evidence submission without submitting a replacement mutation.",
    ("post", "/api/v1/driver/profile/onboarding/complete"): "Request completion of driver onboarding after required steps; this does not substitute for administrative readiness approval.",
    ("post", "/api/v1/driver/profile/onboarding/progress"): "Persist the driver's onboarding progress for later resumption; progress is distinct from verified eligibility.",
    ("post", "/api/v1/driver/profile/onboarding/step"): "Record a driver onboarding step through the server's step-validation workflow.",
    ("get", "/api/v1/driver/rides/available/seek"): "Read a cursor-paged set of ride requests visible to this driver under current location, readiness and marketplace rules.",
    ("get", "/api/v1/driver/rides/{rideRequestId}/route-preview"): "Read the permitted route preview for a ride request before deciding whether to bid.",
    ("get", "/api/v1/wallet/cashout"): "List the current account's withdrawal requests and their lifecycle states.",
    ("get", "/api/v1/wallet/cashout/limits"): "Read the current withdrawal bounds and applicable plan context before requesting a cashout.",
    ("get", "/api/v1/wallet/cashout/{cashoutId}/status"): "Read the owner's existing withdrawal outcome; pending approval or dispatch is not settlement.",
    ("get", "/api/v1/wallet/topup/limits"): "Read current top-up limits for the resolved account, country and payment context.",
    ("get", "/api/v1/wallet/topup/quote"): "Read a server top-up quote with applicable amount, currency and fee evidence before committing payment.",
    ("get", "/api/v1/wallet/transfers/quote"): "Read a transfer quote before confirmation; retain its recipient, currencies, fees and expiry rather than recalculating them on the device.",
    ("get", "/api/v1/wallet/topups/paypal/{operationId}/status"): "Read the existing PayPal top-up operation's server state without creating a new checkout.",
    ("post", "/api/v1/wallet/topups/paypal/{operationId}/reconcile"): "Ask the server to reconcile the existing PayPal top-up against provider evidence; reuse the original operation instead of creating a second payment.",
    ("get", "/api/v1/wallet/topup/bank-transfers"): "List the account's bank-transfer top-ups awaiting or carrying a review outcome.",
    ("post", "/api/v1/wallet/topup/bank-transfers/{paymentId}/cancel"): "Request cancellation of the account's eligible pending bank-transfer top-up; reconcile if the review state changed concurrently.",
    ("get", "/api/v1/wallet/payout-methods"): "List the account's saved masked payout destinations; returned masking is not sufficient to reconstruct bank credentials.",
    ("post", "/api/v1/wallet/payout-methods"): "Save an eligible payout destination through the account-owned payout-method workflow.",
    ("delete", "/api/v1/wallet/payout-methods/{id}"): "Remove an eligible saved payout method; an outstanding withdrawal can prevent deletion.",
    ("get", "/api/v1/wallet/recipients"): "List saved wallet-transfer recipients for the current account.",
    ("post", "/api/v1/wallet/recipients"): "Add a transfer recipient after the server resolves and validates the intended beneficiary.",
    ("delete", "/api/v1/wallet/recipients/{id}"): "Remove the saved recipient relationship without deleting historical transfers.",
    ("get", "/api/v1/wallet/financial-history"): "Read the account's financial-history projection across supported payment and wallet events.",
    ("get", "/api/v1/wallet/financial-history/{entryId}"): "Read a permitted financial-history entry and its linked transaction facts.",
    ("post", "/api/v1/wallet/financial-history/{entryId}/disputes"): "Open a dispute concerning an eligible financial-history entry; opening a case does not refund money.",
    ("get", "/api/v1/notifications/preferences/effective"): "Read effective notification settings after account preferences and mandatory-category rules are applied.",
    ("get", "/api/v1/notifications/push-token/installation-state"): "Read the current admitted installation's binding revision and enabled state before changing push registration.",
    ("get", "/api/v1/campaign-inbox"): "Read campaigns delivered into the current account's inbox; this is not a campaign-administration interface.",
    ("post", "/api/v1/campaign-inbox/{id}/acknowledge"): "Record the current recipient's acknowledgement of a campaign inbox item.",
    ("get", "/api/v1/trips/active"): "Read the caller's active trip so startup and resume can return to the existing journey.",
    ("get", "/api/v1/trips/history"): "Read authorized completed or historical trip records using this endpoint's pagination contract.",
    ("get", "/api/v1/trips/{tripId}/timeline"): "Read the authorized trip's persisted lifecycle timeline; display order must follow server event evidence.",
    ("get", "/api/v1/trips/{tripId}/pickup-ceremony"): "Read the current pickup-verification ceremony and the next permitted participant action.",
    ("post", "/api/v1/trips/{tripId}/pickup-challenge"): "Create or request the applicable trip-bound pickup challenge before starting the trip.",
    ("get", "/api/v1/trips/{tripId}/pickup-code"): "Read pickup-code information only within the authorized participant ceremony; do not expose it in logs.",
    ("post", "/api/v1/trips/{tripId}/route-alterations"): "Propose a trip route change for the other participant's decision and the server's fare/lifecycle validation.",
    ("post", "/api/v1/trips/{tripId}/route-alterations/{alterationId}/accept"): "Accept the identified route-change proposal under the current trip state; use the returned route and financial facts.",
    ("post", "/api/v1/trips/{tripId}/route-alterations/{alterationId}/reject"): "Reject the identified trip route-change proposal without treating its proposed route as effective.",
    ("get", "/api/v1/rides/{rideRequestId}/no-driver-recovery"): "Read permitted recovery choices when a ride request has not obtained a driver.",
    ("post", "/api/v1/rides/{rideRequestId}/search/extend"): "Request an extension of the current ride search under marketplace policy; it does not guarantee a match.",
    ("get", "/api/v1/voice/call/incoming"): "Read incoming call state for the authenticated participant. Stop polling when the protected session is unavailable.",
    ("get", "/api/v1/voice/options"): "Read available calling options for this context; provider configuration and trip relationship determine actual availability.",
    ("get", "/api/v1/voice/call/{callId}"): "Read an authorized participant call's state and permitted connection information.",
    ("get", "/api/v1/support/tickets/catalog"): "Read supported ticket categories and submission choices before creating a support request.",
    ("get", "/api/v1/support/tickets/operations/outcome"): "Read the original support mutation's outcome without posting a duplicate ticket, reply or state change.",
    ("get", "/api/v1/safety/emergency-number"): "Read the emergency-number information for the server-resolved country; application support is not emergency dispatch.",
    ("get", "/api/v1/reports/exports/{artifactId}"): "Read the authorized export job/artifact status before attempting a download.",
    ("get", "/api/v1/reports/exports/{artifactId}/download"): "Download a ready report artifact after ownership and artifact-validity checks.",
    ("get", "/api/v1/rentals/bookings/{bookingId}/operations"): "Read operation/recovery facts for an authorized rental booking before continuing an interrupted booking or payment workflow.",
    ("get", "/api/v1/rentals/booking-status-contract"): "Read the rental booking state contract used to render supported states and transitions consistently.",
    ("get", "/api/v1/rentals/vehicles/{vehicleId}/quote"): "Read a rental quote for the selected vehicle and booking context; quoted availability is not a confirmed reservation.",
}

MODEL_FIELDS = {
    "ProblemDetails": {
        "status": "HTTP status for this problem response, not a trip/payment lifecycle enum.",
        "type": "Problem-type URI identifying the class of failure; not a resource ID.",
        "title": "Short human-readable summary of the problem class.",
        "detail": "Sanitized explanation of this failure occurrence; display safely and do not interpret it as executable recovery instructions.",
        "instance": "Reference to this problem occurrence when supplied; do not assume it is a public URL.",
        "code": "Machine-readable KiloDrive error category used for client error handling.",
    },
    "RegisterRequest": {
        "role": "Requested consumer role. The shared UserRole enum also contains administrative values, but self-registration does not grant those roles.",
        "countryCode": "Country selected in the immutable registration intent; the server must accept it as an active, provisioned signup country.",
        "createRentalOrganization": "Whether this signup requests the rental-organization onboarding path; it does not make the organization operationally approved.",
        "driverAccountType": "Individual/business driver choice carried from registration intent into the driver profile.",
    },
    "RegisterPushTokenRequest": {
        "token": "Native push-registration token for this installation; distinct from the admitted-device credential and bearer access token.",
        "expectedRevision": "Previously read installation binding revision; prevents a stale callback from overwriting newer opt-out or ownership state.",
        "explicitOptIn": "Explicit user request to enable this installation's notifications; token refresh alone is not renewed consent.",
        "mutationId": "Identity of this binding change, retained for replay/reconciliation after a lost response.",
    },
    "MembershipPlanDto": {
        "code": "Stable catalog plan code; a display-name edit must not be treated as a new entitlement or store product.",
        "description": "Human-readable plan description. It describes the catalog offer, not proof that a member has purchased it.",
        "feeMinor": "Catalog fee for the plan's default period, in currency minor units; explicit term prices have separate fields.",
        "isActive": "Catalog availability flag; native-store mapping, country pricing and purchase eligibility remain separate checks.",
        "sortOrder": "Catalog display ordering; it is not a tier rank for calculating upgrades.",
    },
    "MyMembershipDto": {
        "isActive": "Whether the projected membership is active; use the unified store-status snapshot to combine entitlement with provider recovery facts.",
        "planId": "Current membership catalog plan, when one is assigned; null is not an unknown plan identifier.",
    },
    "MembershipStoreStatusDto": {
        "benefitsActive": "Authoritative result for whether membership benefits currently apply; do not infer this from a future expiry alone.",
        "providerConfirmedExpiresAtUtc": "Expiry established by provider evidence; may differ from policy-defined access-through time.",
        "accessThroughUtc": "Server-projected end of benefit access, including applicable lifecycle policy; not automatically the next billing date.",
        "isChecking": "Whether entitlement/provider reconciliation is in progress; show a checking state instead of offering a blind repurchase.",
        "requiresManualReview": "Whether automated reconciliation requires operator review before the unresolved state can be decided.",
        "source": "Origin of the entitlement projection, separate from the payment provider name.",
        "safeAction": "Typed next action for the current membership state; use this instead of guessing a purchase/restore button from status text.",
        "policyRevision": "Revision of the membership policy used to build this projection, separate from stateRevision.",
    },
    "ProviderBillingDto": {
        "accountId": "Billing subject identifier interpreted with accountType; it is not universally the global user ID.",
        "billingMode": "Configured billing arrangement for this subject; it does not establish entitlement by itself.",
        "availableTermDays": "Durations offered in this billing context; do not assume every catalog term is purchasable.",
        "storeWillAutoRenew": "Provider-reported renewal intent when known; null must not be displayed as a confirmed cancellation.",
    },
    "StoreProductDto": {
        "productId": "Exact native store product identifier in the reviewed mapping; not the membership plan UUID.",
        "googleBasePlanId": "Google subscription base-plan identifier where the mapping uses one.",
        "googleOfferId": "Google offer identifier where an offer applies; it is distinct from the base plan.",
        "canPurchase": "Server eligibility result for this mapping/context; the native storefront must still return the matching offer.",
        "exactLocalizedPrice": "Localized store-price evidence when available; absence must not be replaced with an invented payable store price.",
        "description": "Human-readable store-product description; the mapped plan and native offer establish the actual purchase.",
    },
    "WalletDto": {
        "amounts": "Server-calculated wallet breakdown used to distinguish ledger, held and spendable amounts.",
        "transferSendEnabled": "Whether the account is enabled to initiate transfers; per-transfer validation and limits still apply.",
        "transferReceiveEnabled": "Whether the account is enabled to receive transfers; this does not guarantee acceptance of every transfer.",
        "topUpEnabled": "Whether top-ups are enabled for the account; provider and amount checks remain separate.",
    },
    "DriverReadinessDto": {
        "driversLicenseVerified": "Current licence-verification assessment; a stored upload alone is not a reviewed licence.",
        "complianceHash": "Fingerprint identifying the assessed compliance evidence; not a bearer credential or independent approval.",
        "vehicleAssigned": "Whether an applicable vehicle assignment exists for this driver.",
        "primaryVehicleVerified": "Whether the assessed primary vehicle has passed the required verification checks.",
        "registrationCurrent": "Whether the assessed vehicle registration is current under the readiness policy.",
        "insuranceCurrent": "Whether the assessed vehicle insurance is current under the readiness policy.",
        "fitnessCurrent": "Whether the assessed fitness requirement is current under the applicable policy.",
        "dutyEligible": "Whether duty-time policy currently permits work; membership does not override this check.",
        "locationFresh": "Whether the server considers the driver's latest location fresh enough for the assessed work action.",
        "hasActiveAssignment": "Whether the readiness assessment found an existing work assignment relevant to accepting more work.",
        "bidGateCode": "Specific server gate responsible for the current bidding decision.",
        "onlineGateCode": "Specific server gate responsible for the current online-status decision.",
    },
}
