#!/usr/bin/env python3
"""Generate public version facts from a clean product checkout, never deployment guesses."""

import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

from native_handbook import ROOT, SNAPSHOT_PATH, source_schema_version, source_version

FACTS = ROOT / "docs/architecture/source-versions.generated.md"


def current_row_matches(content, label, value):
    return bool(re.search(
        rf"(?m)^\| {re.escape(label)} \| `{re.escape(value)}` \|", content
    ))


def read_values(source_root):
    return {
        "consumerVersion": source_version(source_root / "src/client/mobile/pubspec.yaml"),
        "systemAdminVersion": source_version(source_root / "src/client/system_admin/pubspec.yaml"),
        "schemaContract": source_schema_version(source_root / "src/server/KiloDrive.Api/Data/SchemaContract.cs"),
        "privateOpenApiSha256": hashlib.sha256(
            (source_root / "docs/contracts/openapi/kilodrive-v1.json").read_bytes()
        ).hexdigest(),
    }


def render(snapshot):
    lines = [
        "# Source-derived version facts", "",
        "Generated by `tools/source_baseline.py` from the product checkout. Do not edit.", "",
        "| Item | Source value |", "| --- | --- |",
    ]
    for label, key in (
        ("Reviewed date", "reviewedDate"), ("Product revision", "productSourceRevision"),
        ("Consumer", "consumerVersion"), ("System Admin", "systemAdminVersion"),
        ("Schema contract", "schemaContract"), ("Private v1 contract SHA-256", "privateOpenApiSha256"),
    ):
        lines.append(f"| {label} | `{snapshot[key]}` |")
    lines.extend([
        "", "Source versions are not deployed-runtime versions or store-availability claims.",
        "The curated public API export retains its independently recorded provenance.", "",
        "[Current baseline](../current-baseline.md) · [Release updates](release-1.0.0-198.md)", "",
    ])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-root", type=Path)
    parser.add_argument("--reviewed-date")
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    snapshot = json.loads(SNAPSHOT_PATH.read_text(encoding="utf-8"))
    if args.write:
        if not args.source_root or not args.reviewed_date:
            parser.error("--write requires --source-root and --reviewed-date")
        # Ignore untracked local evidence, but reject uncaptured tracked source edits.
        if subprocess.check_output(["git", "status", "--porcelain", "--untracked-files=no"], cwd=args.source_root, text=True).strip():
            parser.error("commit tracked product changes before capturing source provenance")
        snapshot.update(read_values(args.source_root))
        snapshot.update(
            reviewedDate=args.reviewed_date,
            productSourceRevision=subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=args.source_root, text=True).strip(),
            productWorkingTree="tracked product source clean at capture; dated evidence retains its original artifact identity",
        )
        SNAPSHOT_PATH.write_text(json.dumps(snapshot, indent=2) + "\n", encoding="utf-8")
        FACTS.write_text(render(snapshot), encoding="utf-8")
    errors = []
    if not FACTS.exists() or FACTS.read_text(encoding="utf-8") != render(snapshot):
        errors.append("source version facts drift; regenerate from committed product source")
    for page in ("README.md", "docs/current-baseline.md"):
        content = (ROOT / page).read_text(encoding="utf-8")
        for key in ("consumerVersion", "systemAdminVersion", "schemaContract", "productSourceRevision"):
            if snapshot[key] not in content:
                errors.append(f"{page} does not contain captured {key}")
        labels = (
            ("Consumer app source, current observation", "System Admin app source, current observation", "Schema contract, current observation")
            if page == "README.md" else ("Consumer source", "System Admin source", "Schema contract")
        )
        for label, key in zip(labels, ("consumerVersion", "systemAdminVersion", "schemaContract")):
            if not current_row_matches(content, label, snapshot[key]):
                errors.append(f"{page} current {label} row differs from source snapshot")
    if args.source_root:
        for key, value in read_values(args.source_root).items():
            if snapshot[key] != value:
                errors.append(f"captured {key} differs from authoritative source")
        revision = subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=args.source_root, text=True
        ).strip()
        if snapshot["productSourceRevision"] != revision:
            errors.append("captured product revision differs from authoritative source")
    for error in errors:
        print(f"ERROR: {error}", file=sys.stderr)
    if errors:
        return 1
    print("Source-derived documentation facts: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
